### ISSUE TITLE
Problem on using All vs Single

### ISSUE THREAD

**Issue by walker10AT** [Shaenn/ShaNetHoliday#119]
I do not get the same results when I'm using the following code:

   var all = HolidaySystem.Instance.All(2000, Alpha2.CN, RuleType.All);
            var single = HolidaySystem.Instance.Single(new DateTime(2000, 1, 1), Alpha2.CN, RuleType.All);

In the List of all, the 1st of Jan 2000 is a public holiday and if I compare it with the single instance, it says, that the 1st Jan 2000 is no public holiday in CN?

Is this a known issue, or do I use the code wrong?

Thank you very much

Best Regards

**Comment by Shaenn** [comment]
Hello, 
The 1st of Jan, is of rule type Public, 

Try the single method with Public instead of All.

Best regards, 

Shaenn

**Comment by walker10AT** [comment]
Hello Shaenn,

thank you very much! Is working now!

Best Regards
